name: Smoketest - Sandbox Form

on:
  schedule:
    - cron: '20 * * * *'
  workflow_dispatch:

env:
  CYPRESS_SINGLE_SPEC: true

jobs:
  cypress_smoketest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Add private key for sandbox-access-form repo
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SANDBOX_FORM_SSH_KEY }}

      - name: NPM Install
        run: npm ci

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          config: baseUrl=https://dev-developer.va.gov
          install: false
          spec: cypress/e2e/smoketest.cy.js

      - name: Upload failed screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload failed videos
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
          working-directory: 'smoketest'

      - name: Install jq
        run: |
          sudo apt update;
          sudo apt install -y jq;

      - name: Delete smoketest Okta apps
        env:
          OKTA_BASE_URL: 'https://deptva-eval.okta.com/api/v1'
          OKTA_TOKEN: ${{ secrets.OKTA_TOKEN }}
        run: |
          cd smoketest;
          for acgClientId in `grep clientID ../cypress/downloads/sandbox-* | grep -v null | cut -d \" -f4`; do
            echo "Deleting ACG Client: $acgClientId";
            bundle exec ruby ./delete-smoketest-apps.rb $acgClientId;
            sleep 5;
          done
          for ccgClientId in `grep ccgClientId ../cypress/downloads/sandbox-* | grep -v null | cut -d \" -f4`; do
            echo "Deleting CCG Client: $ccgClientId";
            bundle exec ruby ./delete-smoketest-apps.rb $ccgClientId;
            sleep 5;
          done

      - name: Send Slack notification for a failed signup
        uses: slackapi/slack-github-action@v1.23.0
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel-id: C012L7SRG66
          # This ID is for #vaapi-alerts in Lighthouse Slack
          payload: |
            {
              "text": "Developer Portal Sandbox Signup Form Smoketest: ${{ job.status }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Developer Portal Sandbox Signup Form Smoketest:\n*Status: ${{ job.status }}*"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "@teamokapi please investigate"
                  }
                }
              ]
            }
