name: Privileged Visual Regressions
# The workflow "Unprivileged Visual Regressions" does not have access to repository secrets.
# Any files received through the incoming GitHub artifacts must be treated as static and not executed.

on:
  workflow_run:
    workflows: ['Unprivileged Visual Regressions']
    types:
      - completed

jobs:
  visual_comment:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion != 'success' }}
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Download Screenshot Artifacts
        uses: actions/github-script@v3.1.0
        with:
          script: |
            var artifacts = await github.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: ${{ github.event.workflow_run.id }},
            });
            var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "visual-test-failures"
            })[0];
            var download = await github.actions.downloadArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              artifact_id: matchArtifact.id,
              archive_format: 'zip',
            });
            var fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/visual-test-failures.zip', Buffer.from(download.data));

      - name: Unzip
        run: |
          mkdir image_diffs
          unzip visual-test-failures.zip -d image_diffs

      - id: get_pr_info
        name: Get PR and hash data
        run: |
          PR_NUMBER=`cat ./image_diffs/pr.txt`
          COMMIT_HASH=`cat ./image_diffs/hash.txt`
          PREVIOUS_GITHUB_HEAD_REF=`cat ./image_diffs/branch.txt`
          echo $PR_NUMBER
          echo $COMMIT_HASH
          echo $PREVIOUS_GITHUB_HEAD_REF
          rm ./image_diffs/pr.txt ./image_diffs/hash.txt ./image_diffs/branch.txt
          echo "::set-output name=pr::$PR_NUMBER"
          echo "::set-output name=hash::$COMMIT_HASH"
          echo "::set-output name=branch_name::$PREVIOUS_GITHUB_HEAD_REF"

      - uses: actions/checkout@v2
        with:
          lfs: true
          ref: ${{ steps.get_pr_info.outputs.branch_name }}

      - name: Redownload Screenshot Artifacts after branch change
        uses: actions/github-script@v3.1.0
        with:
          script: |
            var artifacts = await github.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: ${{ github.event.workflow_run.id }},
            });
            var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "visual-test-failures"
            })[0];
            var download = await github.actions.downloadArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              artifact_id: matchArtifact.id,
              archive_format: 'zip',
            });
            var fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/visual-test-failures.zip', Buffer.from(download.data));

      - name: Unzip again and delete metadata files
        run: |
          mkdir image_diffs
          unzip visual-test-failures.zip -d image_diffs
          rm ./image_diffs/pr.txt ./image_diffs/hash.txt ./image_diffs/branch.txt

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{secrets.AWS_REGION}}
          role-to-assume: ${{secrets.AWS_ROLE_ARN}}
          role-duration-seconds: 1200
          role-session-name: GitHubActions

      - name: Upload failures
        env:
          AWS_REGION: ${{secrets.AWS_REGION}}
          AWS_S3_SCREENSHOTS_BUCKET: ${{secrets.AWS_S3_SCREENSHOTS_BUCKET}}
          COMMIT_HASH: ${{steps.get_pr_info.outputs.hash}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          PR_NUMBER: ${{steps.get_pr_number.outputs.pr}}
          PR_BRANCH_NAME: ${{steps.get_pr_number.outputs.branch_name}}
        run: |
          aws s3 sync --no-progress --acl public-read image_diffs/ s3://$AWS_S3_SCREENSHOTS_BUCKET/$PR_BRANCH_NAME/gha-$COMMIT_HASH/
          report_path="image_diffs/"
          links=""
          for f in ${report_path}*; do
            links="${links} - [${f#"${report_path}"}](https://s3-${AWS_REGION}.amazonaws.com/${AWS_S3_SCREENSHOTS_BUCKET}/$PR_BRANCH_NAME/gha-${COMMIT_HASH}/${f#"${report_path}"}) <br />"
          done
          docsLink="https://github.com/$GITHUB_REPOSITORY/blob/master/docs/testing.md#visual-regression-testing"
          comment="Visual regression testing failed. Review these diffs and then [update the snapshots locally or with GitHub Actions](${docsLink}). <br><br> ${links}"
          gh pr comment $PR_NUMBER --body "$comment"
