name: Unprivileged Visual Regressions
# Unprivileged relates to this job being able to be run by a user without write permissions.
# A PR from a forked repo can safely run this job as there are no repository secrets available to it.
on:
  pull_request:
    branches: [master, node-18-upgrade]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  visual:
    runs-on: ubuntu-latest
    container: cypress/included:12.8.1
    env:
      CYPRESS_SINGLE_SPEC: true
      failOnSnapshotDiff: false
    outputs:
      node_version: ${{ steps.node_version.outputs.node_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - id: node_version
        name: Set Node Version to ENV
        run: |
          env
          NODE_VERSION=$(node -v)
          echo $NODE_VERSION
          echo "::set-output name=node_version::$NODE_VERSION"

      - id: pr_number
        name: Get PR Number
        run: |
          PR_NUMBER=`printf $GITHUB_REF | sed 's|refs/pull/||' | sed 's|/merge||'`
          echo $PR_NUMBER
          echo "::set-output name=pr::$PR_NUMBER"

      - id: githash
        name: Set git hash
        run: |
          GIT_HASH=$(/bin/bash -c "git log --oneline | cut -f3 -d \" \" | cut -c1-7")
          echo $GIT_HASH
          echo "::set-output name=hash::$GIT_HASH"

      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Update apt-get and install packages
        run: sudo apt-get update && sudo apt-get install -y libxss1 libxtst6 wget --no-install-recommends
      - name: Install Google apt-get key
        run: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
      - name: Install Google apt-get source
        run: sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
      - name: Install Chrome and fonts
        run: sudo apt-get update && sudo apt-get install -y google-chrome-unstable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf --no-install-recommends
      - name: Remove unnecessary files
        run: sudo rm -rf /var/lib/apt/lists/* \
          && sudo apt-get purge --auto-remove -y curl
          && sudo rm -rf /src/*.deb

      - name: Install python env
        run: |
          apt update && apt install python3 -y && ln -s /usr/bin/python3 /usr/bin/python
      - name: Install bzip2
        run: apt install bzip2

      - name: Start Fake LPB Server
        run: ./scripts/fake_lpb.sh

      - id: visual_test
        continue-on-error: true
        name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          install-command: npm ci --legacy-peer-deps
          spec: cypress/e2e/visual.cy.js
          start: npm start
          wait-on: http://localhost:3001
          wait-on-timeout: 180

      - name: Add PR and hash to artifact
        if: steps.visual_test.outcome == 'failure'
        env:
          COMMIT_HASH: ${{steps.githash.outputs.hash}}
          PR_NUMBER: ${{steps.pr_number.outputs.pr_number}}
        run: |
          mkdir -p test/image_snapshots/__diff_output__;
          echo $PR_NUMBER > test/image_snapshots/__diff_output__/pr.txt
          echo $COMMIT_HASH > test/image_snapshots/__diff_output__/hash.txt
          echo $GITHUB_HEAD_REF > test/image_snapshots/__diff_output__/branch.txt

      - name: Add overview failure graphics to archive
        if: steps.visual_test.outcome == 'failure'
        run: |
          cp cypress/screenshots/* test/image_snapshots/__diff_output__/

      - name: Upload failed screenshots
        if: steps.visual_test.outcome == 'failure'
        uses: actions/upload-artifact@v2
        with:
          name: visual-test-failures
          path: test/image_snapshots/__diff_output__

      - name: Report Success/Failure
        if: steps.visual_test.outcome == 'failure'
        run: exit 1
        # This is needed as a unique step due to the continue-on-error set above in visual_test.
        # Images get uploaded to the s3 bucket from within visual-regressions-privileged.yml
